magento_app:
  build: .
  container_name: magento_app
  external_links:
    - mysql
  environment:
    - 'VIRTUAL_HOST=magento2.192.168.99.100.xip.io,magento2.192.168.0.16.xip.io'
  volumes:
    - './data:/var/www/html'